import { useState } from "react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export default function Converter() {
  const [vrpCode, setVrpCode] = useState("");
  const [qbcoreCode, setQbcoreCode] = useState("");

  const convertCode = () => {
    let converted = vrpCode
      .replace(/vRP\.getUserSource\((.*?)\)/g, "QBCore.Functions.GetPlayer($1).PlayerData.source")
      .replace(/vRP\.getUserId\((.*?)\)/g, "QBCore.Functions.GetPlayer($1).PlayerData.citizenid")
      .replace(/vRP\.addBankMoney\((.*?),\s*(.*?)\)/g, "QBCore.Functions.GetPlayer($1).Functions.AddMoney('bank', $2)")
      .replace(/vRP\.tryPayment\((.*?),\s*(.*?)\)/g, "QBCore.Functions.GetPlayer($1).Functions.RemoveMoney('cash', $2)")
      .replace(/vRP\.getUserIdentity\((.*?)\)/g, "QBCore.Functions.GetPlayer($1).PlayerData")
      .replace(/vRP\.setUserGroup\((.*?),\s*(.*?)\)/g, "QBCore.Functions.GetPlayer($1).Functions.SetJob($2)");
    
    setQbcoreCode(converted);
  };

  return (
    <div className="p-6 max-w-2xl mx-auto">
      <h1 className="text-2xl font-bold mb-4">vRP to QBCore Converter</h1>
      <Textarea
        className="w-full h-40 p-2 border rounded"
        placeholder="vRP Lua 코드를 입력하세요"
        value={vrpCode}
        onChange={(e) => setVrpCode(e.target.value)}
      />
      <Button className="mt-4 w-full" onClick={convertCode}>
        변환하기
      </Button>
      <Textarea
        className="w-full h-40 p-2 border rounded mt-4"
        placeholder="QBCore Lua 코드 출력"
        value={qbcoreCode}
        readOnly
      />
    </div>
  );
}
